[versions]
kotlin = "1.9.24" # Move to 2.0 when v1.10 is released
antlr-kotlin = "1.0.0"

[libraries]
antlr-kotlin =  { module = "com.strumenta:antlr-kotlin-runtime", version.ref = "antlr-kotlin" }


[plugins]
antlr-kotlin =  { id = "com.strumenta.antlr-kotlin", version.ref = "antlr-kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
